### ISSUE TITLE
NP Coin wallet cannot be synchronized

### ISSUE THREAD

**Issue by fajarcdc** [npcoincoreteam/npcoin-core#1]
![Screenshot_14](https://user-images.githubusercontent.com/41838819/62806916-4b678800-bb1e-11e9-9b9c-98962fb5fc96.png)
![Screenshot_15](https://user-images.githubusercontent.com/41838819/62806920-4efb0f00-bb1e-11e9-8409-b96053fcee15.png)

Why NP Coin wallet can't sync?

**Comment by npcoincoreteam** [comment]
We have fix it with new wallet version
